# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clientmessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='clientmessage.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x13\x63lientmessage.proto\"\xca\x02\n\x1b\x43lientToTransferNodeMessage\x12\x36\n\x04type\x18\x01 \x01(\x0e\x32(.ClientToTransferNodeMessage.MessageType\x12#\n\x08\x61uthData\x18\x02 \x01(\x0b\x32\x11.AuthenticateData\x12#\n\tstartData\x18\x03 \x01(\x0b\x32\x10.StartUploadData\x12\x1f\n\nuploadData\x18\x04 \x01(\x0b\x32\x0b.UploadData\x12#\n\x0c\x66inishedData\x18\x05 \x01(\x0b\x32\r.FinishedData\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\"P\n\x0bMessageType\x12\x10\n\x0c\x41UTHENTICATE\x10\x00\x12\x10\n\x0cSTART_UPLOAD\x10\x01\x12\x0f\n\x0bUPLOAD_DATA\x10\x02\x12\x0c\n\x08\x46INISHED\x10\x03\"\x1f\n\x10\x41uthenticateData\x12\x0b\n\x03key\x18\x01 \x01(\t\"C\n\x0fStartUploadData\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x10\n\x08mimetype\x18\x02 \x01(\t\x12\x0c\n\x04size\x18\x03 \x01(\x04\"7\n\nUploadData\x12\r\n\x05order\x18\x01 \x01(\x04\x12\x0c\n\x04size\x18\x02 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\".\n\x0c\x46inishedData\x12\r\n\x05\x65rror\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CLIENTTOTRANSFERNODEMESSAGE_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='ClientToTransferNodeMessage.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AUTHENTICATE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='START_UPLOAD', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPLOAD_DATA', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FINISHED', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=274,
  serialized_end=354,
)
_sym_db.RegisterEnumDescriptor(_CLIENTTOTRANSFERNODEMESSAGE_MESSAGETYPE)


_CLIENTTOTRANSFERNODEMESSAGE = _descriptor.Descriptor(
  name='ClientToTransferNodeMessage',
  full_name='ClientToTransferNodeMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ClientToTransferNodeMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='authData', full_name='ClientToTransferNodeMessage.authData', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='startData', full_name='ClientToTransferNodeMessage.startData', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uploadData', full_name='ClientToTransferNodeMessage.uploadData', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='finishedData', full_name='ClientToTransferNodeMessage.finishedData', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ClientToTransferNodeMessage.timestamp', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CLIENTTOTRANSFERNODEMESSAGE_MESSAGETYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=354,
)


_AUTHENTICATEDATA = _descriptor.Descriptor(
  name='AuthenticateData',
  full_name='AuthenticateData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='AuthenticateData.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=387,
)


_STARTUPLOADDATA = _descriptor.Descriptor(
  name='StartUploadData',
  full_name='StartUploadData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='StartUploadData.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mimetype', full_name='StartUploadData.mimetype', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='StartUploadData.size', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=389,
  serialized_end=456,
)


_UPLOADDATA = _descriptor.Descriptor(
  name='UploadData',
  full_name='UploadData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order', full_name='UploadData.order', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='UploadData.size', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='UploadData.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=458,
  serialized_end=513,
)


_FINISHEDDATA = _descriptor.Descriptor(
  name='FinishedData',
  full_name='FinishedData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='FinishedData.error', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='success', full_name='FinishedData.success', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=515,
  serialized_end=561,
)

_CLIENTTOTRANSFERNODEMESSAGE.fields_by_name['type'].enum_type = _CLIENTTOTRANSFERNODEMESSAGE_MESSAGETYPE
_CLIENTTOTRANSFERNODEMESSAGE.fields_by_name['authData'].message_type = _AUTHENTICATEDATA
_CLIENTTOTRANSFERNODEMESSAGE.fields_by_name['startData'].message_type = _STARTUPLOADDATA
_CLIENTTOTRANSFERNODEMESSAGE.fields_by_name['uploadData'].message_type = _UPLOADDATA
_CLIENTTOTRANSFERNODEMESSAGE.fields_by_name['finishedData'].message_type = _FINISHEDDATA
_CLIENTTOTRANSFERNODEMESSAGE_MESSAGETYPE.containing_type = _CLIENTTOTRANSFERNODEMESSAGE
DESCRIPTOR.message_types_by_name['ClientToTransferNodeMessage'] = _CLIENTTOTRANSFERNODEMESSAGE
DESCRIPTOR.message_types_by_name['AuthenticateData'] = _AUTHENTICATEDATA
DESCRIPTOR.message_types_by_name['StartUploadData'] = _STARTUPLOADDATA
DESCRIPTOR.message_types_by_name['UploadData'] = _UPLOADDATA
DESCRIPTOR.message_types_by_name['FinishedData'] = _FINISHEDDATA

ClientToTransferNodeMessage = _reflection.GeneratedProtocolMessageType('ClientToTransferNodeMessage', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTTOTRANSFERNODEMESSAGE,
  __module__ = 'clientmessage_pb2'
  # @@protoc_insertion_point(class_scope:ClientToTransferNodeMessage)
  ))
_sym_db.RegisterMessage(ClientToTransferNodeMessage)

AuthenticateData = _reflection.GeneratedProtocolMessageType('AuthenticateData', (_message.Message,), dict(
  DESCRIPTOR = _AUTHENTICATEDATA,
  __module__ = 'clientmessage_pb2'
  # @@protoc_insertion_point(class_scope:AuthenticateData)
  ))
_sym_db.RegisterMessage(AuthenticateData)

StartUploadData = _reflection.GeneratedProtocolMessageType('StartUploadData', (_message.Message,), dict(
  DESCRIPTOR = _STARTUPLOADDATA,
  __module__ = 'clientmessage_pb2'
  # @@protoc_insertion_point(class_scope:StartUploadData)
  ))
_sym_db.RegisterMessage(StartUploadData)

UploadData = _reflection.GeneratedProtocolMessageType('UploadData', (_message.Message,), dict(
  DESCRIPTOR = _UPLOADDATA,
  __module__ = 'clientmessage_pb2'
  # @@protoc_insertion_point(class_scope:UploadData)
  ))
_sym_db.RegisterMessage(UploadData)

FinishedData = _reflection.GeneratedProtocolMessageType('FinishedData', (_message.Message,), dict(
  DESCRIPTOR = _FINISHEDDATA,
  __module__ = 'clientmessage_pb2'
  # @@protoc_insertion_point(class_scope:FinishedData)
  ))
_sym_db.RegisterMessage(FinishedData)


# @@protoc_insertion_point(module_scope)
